sudo: required
services: 
  - docker
before_install:
  #Download google cloud sdk
  - openssl aes-256-cbc -K $encrypted_8f011423da3c_key -iv $encrypted_8f011423da3c_iv -in services-account.json.enc -out services-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
