apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: k8s-sample-com-tls
spec:
  secretName: k8s-sample-com
  issuerRef: 
   name: letsencrypt-prod
   kind: ClusterIssuer
  commonName: k8s-sample.com
  dnsNames:
    - k8s-sample.com
    - www.k8s-sample.com
  acme:
    config:
      - http01: 
          ingressClass: nginx
        domains:
          - k8s-sample.com
          - www.k8s-sample.com